const GalleryData = [
  {
    id: 44,
    img: "https://images.creativemarket.com/0.1.0/ps/865047/300/200/m1/fpnw/wm0/prez-apple-.jpg?1450875203&s=5f8a9fe0b0502f2e8e295c40bc038241",
    category: "3D",
    name: "iBundle",
    description: "This is a Bundle of Apple products 3D",
    link: "https://creativemarket.com/Xpshl/479082-iBundle",
  },
  {
    id: 45,
    img: "https://images.creativemarket.com/0.1.0/ps/3263175/300/200/m1/fpnw/wm0/iphone_x_space_graysilver_main_1160_-.jpg?1505662571&s=de41903f3e3e8c0a9130a5b700dfd725",
    category: "3D",
    name: "Apple iPhone X Silver... ",
    description: "Apple iPhone X Silver and Space Gray",
    link: "https://creativemarket.com/obshansky/1854529-Apple-iPhone-X-Silver-and-Space-Gray",
  },
  {
    id: 46,
    img: "https://images.creativemarket.com/0.1.0/ps/434531/300/200/m1/fpnw/wm0/1-.jpg?1447340919&s=d4ea4d762bec666880b03e48a3a7a455",
    category: "3D",
    name: "This is a 13 MacBook Pro 3D",
    description: "You need to have Cinema 4D R15",
    link: "https://creativemarket.com/JeremyPaul/238766-MacBook-Pro-13-retina-3D-model",
  },
  {
    id: 47,
    img: "https://images.creativemarket.com/0.1.0/ps/829598/300/200/m1/fpnw/wm0/turbo-.jpg?1449279954&s=ae899ec3f24898832cfa52e9466c4cc9",
    category: "3D",
    name: "Microsoft surface pro 3",
    description: "Detailed High model of Microsoft  ",
    link: "https://creativemarket.com/sprinter880/461151-Microsoft-surface-pro-3",
  },

  {
    id: 48,
    img: "https://images.creativemarket.com/0.1.0/ps/1879471/300/200/m1/fpnw/wm0/nikon_coolpix_l120_preview_w_1160_772-.jpg?1478861451&s=4b7427cbd495718b816fd4eb6216f818",
    category: "3D",
    name: "Nikon CoolPix L 120",
    description: "Nikon CoolPix L 120 low-poly 3d  ",
    link: "https://creativemarket.com/obshansky/1037832-Nikon-CoolPix-L-120",
  },

  {
    id: 49,
    img: "https://images.creativemarket.com/0.1.0/ps/1872334/300/200/m1/fpnw/wm0/echo-dot-001-.jpg?1478733884&s=f2f4f03410276365310892ee79e63b53",
    category: "3D",
    name: "An Amazon Echo Dot ",
    description: "An Amazon Echo Dot [TM] built",
    link: "https://creativemarket.com/KJPargeterImages/1033251-Amazon-Echo-Dot-Black",
  },

  {
    id: 1,
    img: "Images/0ad04233827550.56b9c87740b00.jpg",
    category: "Mockup",
    name: "Shoping Bag",
    description: "Shoping Bag Mockup",
    link: "http://graphicgoogle.com/shopping-bag-mockup/",
  },
  {
    id: 2,
    img: "Images/2-Wine-Bottles-Free-Mockup-550x367.jpg",
    category: "Mockup",
    name: "2-Wine-Bottles-Free-Mockup",
    description: "2-Wine-Bottles-Free-Mockup",
    link: "https://pixelbuddha.net/mockups/cosmetic-travel-bottles-mockups",
  },
  {
    id: 3,
    img: "Images/2xA4-Bifold-Brochure-Mockup.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "2xA4-Bifold-Brochure-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 4,
    img: "Images/2xA4-Bifold-Brochure-Mockup1.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "2xA4-Bifold-Brochure-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 5,
    img: "Images/3xA4-Trifold-Brochure-Mockup.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "2xA4-Bifold-Brochure-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 6,
    img: "Images/3xA4-Trifold-Brochure-Mockup1.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "3xA4-Trifold-Brochure-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 7,
    img: "Images/5de26540114957.5772cd8eb8ef5.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "2xA4-Bifold-Brochure-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 8,
    img: "Images/6b571931219771.5646373b7c2d2.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "2xA4-Bifold-Brochure-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 9,
    img: "Images/9d189a35241229.56ef930116e7c.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "2xA4-Bifold-Brochure-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 10,
    img: "Images/95ecfa35241229.56ef930116783.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "2xA4-Bifold-Brochure-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 11,
    img: "Images/45342740114957.5772cd8eb7da0.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "2xA4-Bifold-Brochure-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 12,
    img: "Images/A4-Brochure-Catalog-Mock-Ups.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "A4-Brochure-Catalog-Mock-Ups",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 13,
    img: "Images/A4-BrochureCatalog-Mock-Ups1.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "A4-Brochure-Catalog-Mock-Ups",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 14,
    img: "Images/A4-Landscape-Brochure.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "A4-Landscape-Brochure",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 15,
    img: "Images/A4-Landscape-Brochure1.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "A4-Landscape-Brochure",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 16,
    img: "Images/A4-Trifold-Brochure-Mock1Ups.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "A4-Trifold-Brochure-Mock",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 17,
    img: "Images/A4-Trifold-Brochure-Mock-Ups.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "A4-Trifold-Brochure-Mock-Ups",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 18,
    img: "Images/bc503f31899177.5665ea95e8bbe.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "A4-Landscape-Brochure",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 19,
    img: "Images/Book-Mockup-Set-820x547.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "Book-Mockup-Set-820x547",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 20,
    img: "Images/DL-Brochure-Magazine-Mockup.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "DL-Brochure-Magazine-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 21,
    img: "Images/DL-Brochure-Magazine-Mockup1.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "DL-Brochure-Magazine-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 22,
    img: "Images/Elite-Book-Title-Mockup.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "Elite-Book-Title-Mockup",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 23,
    img: "Images/f040b331219771.5646373b7567a.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "Book-Mockup-Set-820x547",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 24,
    img: "Images/Free-A5-Bi-Fold-Brochure-Cover-Mockup-550x367.jpg",
    category: "Brochure",
    name: "Brochure",
    description: "Book-Mockup-Set-820x547",
    link: "https://pixelsdesign.net/free-a5-bi-fold-brochure-cover-mockup/",
  },
  {
    id: 25,
    img: "Images/FREE-T-SHIRT-PSD-MOCKUP-FOR-PHOTOSHOP1.jpg",
    category: "SHIRT-PSD-MOCKUP",
    name: "Brochure",
    description: "Book-Mockup-Set-820x547",
    link: "https://crella.net/product/free-t-shirt-psd-mockup-for-photoshop/",
  },
  {
    id: 26,
    img: "Images/FREE-T-SHIRT-PSD-MOCKUP-FOR-PHOTOSHOP.jpg",
    category: "SHIRT-PSD-MOCKUP",
    name: "Brochure",
    description: "FREE-T-SHIRT-PSD-MOCKUP-FOR-PHOTOSHOP",
    link: "https://crella.net/product/free-t-shirt-psd-mockup-for-photoshop/",
  },
  {
    id: 27,
    img: "Images/Free-Sweatshirt-Mockup.jpg",
    category: "SHIRT-PSD-MOCKUP",
    name: "Brochure",
    description: "Free-Sweatshirt-Mockup",
    link: "https://psdkits.com/free-sweatshirt-mockup/",
  },
  {
    id: 28,
    img: "Images/Free-Woman-With-Polo-T-Shirt-Mockup-PSD.jpg",
    category: "SHIRT-PSD-MOCKUP",
    name: "Brochure",
    description: "Free-Woman-With-Polo-T-Shirt-Mockup",
    link: "free-woman-with-polo-t-shirt-mockup-psd/",
  },
  {
    id: 29,
    img: "Images/Free-Woman-With-Polo-T-Shirt-Mockup-PSD-1.jpg",
    category: "SHIRT-PSD-MOCKUP",
    name: "Brochure",
    description: "Free-Woman-With-Polo-T-Shirt-Mockup",
    link: "free-woman-with-polo-t-shirt-mockup-psd/",
  },
  {
    id: 30,
    img: "Images/Girl-T-Shirt-Mockup-1.jpg",
    category: "SHIRT-PSD-MOCKUP",
    name: "Brochure",
    description: "Girl-T-Shirt-Mockup",
    link: "http://graphicgoogle.com/free-girl-t-shirt-mockup/",
  },
  {
    id: 31,
    img: "Images/Girl-T-Shirt-Mockup-1.jpg",
    category: "SHIRT-PSD-MOCKUP",
    name: "Brochure",
    description: "Girl-T-Shirt-Mockup",
    link: "http://graphicgoogle.com/free-girl-t-shirt-mockup/",
  },
  {
    id: 32,
    img: "Images/Girl-T-Shirt-Mockup-2.jpg",
    category: "SHIRT-PSD-MOCKUP",
    name: "Brochure",
    description: "Girl-T-Shirt-Mockup",
    link: "http://graphicgoogle.com/free-girl-t-shirt-mockup/",
  },
  {
    id: 33,
    img: "Images/Cap-Mockup-PSD-100-DesignYep-com.jpg",
    category: "SHIRT-PSD-MOCKUP",
    name: "Brochure",
    description: "Cap-Mockup-PSD-100-Design",
    link: "http://graphicgoogle.com/free-woman-with-polo-t-shirt-mockup-psd/",
  },
  {
    id: 34,
    img: "Images/2-Wine-Bottles-Free-Mockup-550x367.jpg",
    category: "Bottles",
    name: "Bottles",
    description: "2-Wine-Bottles-Free-Mockup",
    link: "https://creativemarket.com/search?q=Wine+Bottles&categoryIDs=2",
  },
  {
    id: 35,
    img: "Images/Free-Beverage-Bottle-Mockup-PSD-2018.jpg",
    category: "Bottles",
    name: "Bottles",
    description: "Free-Beverage-Bottle-Mockup-PSD",
    link: "https://creativemarket.com/search?q=Wine+Bottles&categoryIDs=2",
  },
  {
    id: 36,
    img: "Images/milk-bottle-free-mockup-psd-download-550x367.jpg",
    category: "Bottles",
    name: "Bottles",
    description: "milk-bottle-free-mockup-psd",
    link: "https://creativemarket.com/search?q=milk+Bottles&categoryIDs=2",
  },
  {
    id: 37,
    img: "Images/Multisize-Soda-Can-Mockup.jpg",
    category: "Bottles",
    name: "Bottles",
    description: "Multisize-Soda-Can-Mockup",
    link: "https://creativemarket.com/ToaSin/5664176-Multisize-Soda-Can-Mockup?u=ToaSin&utm_source=Link&utm_medium=CM+Social+Share&utm_campaign=Product+Social+Share&utm_content=Multisize+Soda+Can+Mockup&ts=202102",
  },
  {
    id: 37,
    img: "Images/Multisize-Soda-Can-Mockup1.jpg",
    category: "Bottles",
    name: "Bottles",
    description: "Multisize-Soda-Can-Mockup",
    link: "https://creativemarket.com/ToaSin/5664176-Multisize-Soda-Can-Mockup?u=ToaSin&utm_source=Link&utm_medium=CM+Social+Share&utm_campaign=Product+Social+Share&utm_content=Multisize+Soda+Can+Mockup&ts=202102",
  },
  {
    id: 38,
    img: "Images/Pill-Bottle-Mockup.jpg",
    category: "Bottles",
    name: "Bottles",
    description: "Pill-Bottle-Mockup",
    link: "https://creativemarket.com/search?q=Pill+Bottles&categoryIDs=2",
  },
  {
    id: 39,
    img: "Images/Pill-Bottle-Mockup1.jpg",
    category: "Bottles",
    name: "Bottles",
    description: "Pill-Bottle-Mockup",
    link: "https://creativemarket.com/search?q=Pill+Bottles&categoryIDs=2",
  },
  {
    id: 40,
    img: "Images/Free-Kitchen-Apron-Mockup.jpg",
    category: "Bottles",
    name: "Bottles",
    description: "Free-Kitchen-Apron-Mockup",
    link: "https://creativemarket.com/search?q=Free+Kitchen&categoryIDs=2",
  },
  {
    id: 41,
    img: "Images/Supplement-Protein-Jar-Label-Mockup1.jpg",
    category: "Bottles",
    name: "Bottles",
    description: "Supplement-Protein-Jar-Label-Mockup",
    link: "https://creativemarket.com/search?q=Supplement+Protein&categoryIDs=2",
  },
  {
    id: 43,
    img: "Images/7a4ebd78297125.5ca117909d9c3.jpg",
    category: "Bottles",
    name: "Bottles",
    description: "Supplement-Protein-Jar-Label-Mockup",
    link: "https://creativemarket.com/search?q=Supplement+Protein&categoryIDs=2",
  },
];

export default GalleryData;
